# fly.toml app configuration file generated for waitlist-manager on 2023-09-26T23:22:25+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "waitlist-manager"
primary_region = "waw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
